from typing import Optional, Dict, Any, Tuple

class StrataReader:
    """Synchronous reader for Strata snapshots.

    Supports local files, HTTP/HTTPS URLs, and S3 URIs.
    Implements the Python buffer protocol for zero-copy reads.
    """

    def __init__(
        self,
        path: str,
        s3_region: Optional[str] = None,
        endpoint_url: Optional[str] = None,
        allow_restricted: bool = False,
    ) -> None: ...
    def size(self) -> int: ...
    def read_at(self, offset: int, length: int) -> bytes: ...
    def read_at_into(self, offset: int, buffer: bytearray) -> int: ...
    def read(self, size: Optional[int] = None) -> bytes: ...
    def readinto(self, buffer: bytearray) -> int:
        """Zero-copy read into a writable buffer (bytearray, numpy array, etc.)."""
        ...

    def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def readable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def writable(self) -> bool: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "StrataReader": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class AsyncStrataReader:
    """Asynchronous reader for Strata snapshots.

    Compatible with asyncio. Supports local files, HTTP/HTTPS, and S3.
    """

    @staticmethod
    async def create(
        path: str,
        s3_region: Optional[str] = None,
        endpoint_url: Optional[str] = None,
        allow_restricted: bool = False,
    ) -> "AsyncStrataReader": ...
    def size(self) -> int: ...
    async def read_at(self, offset: int, length: int) -> bytes: ...
    async def read(self, size: Optional[int] = None) -> bytes: ...
    async def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    async def __aenter__(self) -> "AsyncStrataReader": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class StrataBuilder:
    """Low-level snapshot builder for creating Strata archives from Python."""

    def __init__(
        self, output_path: str, block_size: int = 65536, compression: str = "lz4"
    ) -> None: ...
    def add_disk_file(self, path: str) -> None: ...
    def add_memory_file(self, path: str) -> None: ...
    def merge_overlay(
        self, base_path: str, overlay_path: str, thin: bool = False
    ) -> None: ...
    def finalize(self) -> None: ...

def pack(
    output: str,
    disk: Optional[str] = None,
    memory: Optional[str] = None,
    compression: str = "lz4",
    block_size: int = 65536,
    encrypt: bool = False,
    password: Optional[str] = None,
    cdc: bool = False,
    min_chunk: int = 16384,
    avg_chunk: int = 65536,
    max_chunk: int = 131072,
) -> None:
    """Pack disk and/or memory images into a Strata archive."""
    ...

def inspect(path: str) -> Dict[str, Any]: ...
def analyze(path: str) -> Dict[str, float]: ...
def diff(overlay_path: str) -> Dict[str, int]: ...
def keygen(output_dir: Optional[str] = None) -> Tuple[str, str]:
    """Generate Ed25519 keypair for signing. Returns (private_key_path, public_key_path)."""
    ...

def sign_image(image_path: str, key_path: str) -> None: ...
def verify_image(image_path: str, key_path: str) -> None: ...
def snapshot_vm(
    qmp_socket: str, base_path: str, overlay_path: str, output_path: str
) -> None: ...
