"""Type stubs for the hexz_loader Rust extension module."""

from typing import Any, Dict, List, Optional, Tuple, Union

class Reader:
    """Synchronous reader for Hexz snapshots.

    Supports local files, HTTP/HTTPS URLs, and S3 URIs.
    Implements the Python buffer protocol for zero-copy reads.
    """

    def __init__(
        self,
        path: str,
        s3_region: Optional[str] = None,
        endpoint_url: Optional[str] = None,
        allow_restricted: bool = False,
        prefetch_count: int = 0,
        cache_capacity_bytes: Optional[int] = None,
    ) -> None: ...
    def size(self) -> int: ...
    def read(
        self, size: Optional[int] = None, offset: Optional[int] = None
    ) -> bytes: ...
    def _read_at_into(self, offset: int, buffer: bytearray) -> int: ...
    def readinto(self, buffer: bytearray) -> int: ...
    def read_xor_delta(
        self,
        size: int,
        offset: int,
        parent: "Reader",
        base_offset: int,
        element_size: int,
    ) -> bytes: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def metadata(self) -> Dict[str, Any]: ...
    def readable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def writable(self) -> bool: ...
    def flush(self) -> None: ...
    def fileno(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Reader": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __getnewargs__(self) -> Tuple[str]: ...
    def __getstate__(self) -> int: ...
    def __setstate__(self, state: int) -> None: ...

class AsyncReader:
    """Asynchronous reader for Hexz snapshots.

    Compatible with asyncio. Supports local files, HTTP/HTTPS, and S3.
    """

    @staticmethod
    async def create(
        path: str,
        s3_region: Optional[str] = None,
        endpoint_url: Optional[str] = None,
        allow_restricted: bool = False,
        prefetch_count: int = 0,
        cache_capacity_bytes: Optional[int] = None,
    ) -> "AsyncReader": ...
    def size(self) -> int: ...
    async def read(
        self, size: Optional[int] = None, offset: Optional[int] = None
    ) -> bytes: ...
    async def seek(self, offset: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    async def __aenter__(self) -> "AsyncReader": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

class Builder:
    """Low-level snapshot builder for creating Hexz archives."""

    def __init__(
        self,
        output_path: str,
        block_size: int = 65536,
        compression: str = "lz4",
        compression_level: Optional[int] = None,
        dedup: bool = True,
        min_chunk: Optional[int] = None,
        avg_chunk: Optional[int] = None,
        max_chunk: Optional[int] = None,
        parent: Optional[Union[str, List[str]]] = None,
        cdc: bool = False,
        num_workers: int = 0,
    ) -> None: ...
    def add_disk_file(self, path: str) -> None: ...
    def add_memory_file(self, path: str) -> None: ...
    def add_disk_bytes(self, data: Any) -> None: ...
    def add_memory_bytes(self, data: Any) -> None: ...
    def add_xor_delta_bytes(
        self, data: Any, base_offset: int, base_length: int, element_size: int
    ) -> None: ...
    def add_xor_delta_from_buffers(
        self, data: Any, base_data: Any, element_size: int
    ) -> None: ...
    def set_metadata(self, metadata: bytes) -> None: ...
    def get_bytes_written(self) -> int: ...
    def merge_overlay(
        self, base_path: str, overlay_path: str, thin: bool = False
    ) -> None: ...
    def finalize(self) -> None: ...

def pack(
    output: str,
    disk: Optional[str] = None,
    memory: Optional[str] = None,
    compression: str = "lz4",
    block_size: int = 65536,
    encrypt: bool = False,
    password: Optional[str] = None,
    min_chunk: Optional[int] = None,
    avg_chunk: Optional[int] = None,
    max_chunk: Optional[int] = None,
    parallel: bool = True,
    num_workers: int = 0,
    show_progress: bool = True,
) -> None: ...
def store_safetensors(
    input_path: str,
    output_path: str,
    *,
    base: Optional[str] = None,
    compression: str = "zstd",
    block_size: int = 65536,
    show_progress: bool = True,
) -> Dict[str, Any]: ...
def extract_safetensors(
    input_path: str,
    output_path: str,
    *,
    tensor: Optional[str] = None,
) -> None: ...
def load_checkpoint(
    path: str,
    keys: Optional[List[str]] = None,
) -> Dict[str, Any]: ...
def inspect(path: str) -> Dict[str, Any]: ...
def analyze(path: str) -> Dict[str, float]: ...
def diff(overlay_path: str) -> Dict[str, int]: ...
def get_format_version() -> int: ...
def get_min_supported_version() -> int: ...
def get_max_supported_version() -> int: ...
def keygen(output_dir: Optional[str] = None) -> Tuple[str, str]: ...
def sign_image(image_path: str, key_path: str) -> None: ...
def verify_image(image_path: str, key_path: str) -> None: ...
def snapshot_vm(
    qmp_socket: str, base_path: str, overlay_path: str, output_path: str
) -> None: ...
