[package]
name = "hexz-vfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
description = "Platform-agnostic virtual filesystem logic for Hexz"

[lints]
workspace = true

[dependencies]
hexz-core.workspace = true
hexz-common.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
fuser = "0.14"
walkdir = "2.4"
libc = "0.2"
