[package]
name = "hexz-core"
version = "0.1.0-alpha"
edition = "2024"
authors = ["Will McCallion"]
license = "Apache-2.0"
repository = "https://github.com/willmccallion/hexz"
description = "Core engine for high-performance data streaming and compression"

[dependencies]
hexz-common.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
bincode.workspace = true
bytes.workspace = true
tokio.workspace = true
reqwest = { version = "0.11" }

# Compression
lz4_flex = "0.11"
zstd = { version = "0.13", optional = true }

# Crypto
aes-gcm = { version = "0.10", optional = true }
pbkdf2 = { version = "0.12", optional = true }
hmac = { version = "0.12", optional = true }
sha2.workspace = true
blake3 = "1.5"

# Utils
crc32fast = "1.3"
lru = "0.12"
rayon = "1.8"
dashmap = "5.5"
memmap2 = "0.9"
rust-s3 = { version = "0.33", features = ["tokio", "fail-on-err"], optional = true }
openssl = { version = "0.10", features = ["vendored"] }
url = "2.5"
fastcdc = "3.1"

[features]
default = ["compression-zstd", "encryption", "s3", "signing"]

s3 = ["dep:rust-s3"]
compression-zstd = ["dep:zstd"]
encryption = ["dep:aes-gcm", "dep:pbkdf2", "dep:hmac"]
signing = ["hexz-common/signing"]

[dev-dependencies]
tempfile = "3.8"
rand = "0.8"
wiremock = "0.6"
rstest = "0.18"
proptest = "1.0"
