[package]
name = "hexz-fuse"
version = "0.1.0"
edition = "2024"
authors = ["Will McCallion"]
repository = "https://github.com/Alethic-Systems/hexz"
description = "FUSE filesystem adapter for Hexz snapshots"

[dependencies]
hexz-core.workspace = true
hexz-common.workspace = true
anyhow.workspace = true
fuser = "0.14"
libc = "0.2"
tracing.workspace = true
serde.workspace = true
bincode.workspace = true

[dev-dependencies]
tempfile = "3.8"
